# Generated by Django 5.2.1 on 2025-05-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('shipments', '0003_shipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
    ]
